# install.packages("googledrive")
# install.packages("dplyr")
# for pulling files down from Google Drive
# and writing them back
library(googledrive)

rodis_pii_url <- "https://drive.google.com/drive/u/0/folders/1X9Btw83RZR7UG2mIXDEtkY-1nt1r8aQr"
rodis_pii_dribble <- drive_get(rodis_pii_url)

# For general purpose
library(tidyverse)
#2/18/2021 coulda sworn this worked before. Not sure why R isn't looking
# in the working directory, or why /rodis is here, since that folder
# never existed
#source('~/rodis/helpers.R')
source(paste0(getwd(),"/helpers.R"))

# for reading files in
library(haven)
library(readxl)

library(lubridate)

# create people files blocked on gender 
# for subsequent linkages on AWS glue

# Skip all this and go to load statement for a shortcut.

# 9/13/2021 process FamLink records. The original file used quotation marks
# inconsistently, perhaps due in part to truncation. The edited file has
# no quotation marks, and some secondary first names have been moved to
# the middle name field if the initial was the same, and derivative names
# (e.g. Bill) have been deleted if the full name was already there.
# Drop last (empty) row and first row, which is a dummy record.
famlink <- read_delim("raw_data/famlink/CW Involvement and Risk for Injury Study.rpt_edited.txt", 
                      "|", escape_double = FALSE, trim_ws = TRUE) %>% 
  filter(!is.na(ID_PEOPLE_DIM) & ID_PEOPLE_DIM != 1)
famlink_spec_raw <- spec(famlink)
famlink_spec_cols <- enframe(famlink_spec_raw$cols,
                       name = "tx_famlink_var") %>% 
  select(tx_famlink_var) %>% 
  bind_cols(lapply(seq_along(famlink_spec_raw$cols),
                     function(x){
                       class(famlink_spec_raw$cols[[x]])[1]
                     }) %>% enframe(value = "tx_col_type") %>% 
             mutate(tx_col_type = unlist(tx_col_type)) %>% 
             select(tx_col_type)) %>% 
  mutate(tx_col_type = str_replace(tx_col_type,"collector_",""))
famlink_import_errors <- problems(famlink)
error_fields <- famlink_import_errors %>% 
  select(col) %>% 
  group_by(col) %>% 
  count()
# CD_LNG_PRFR and FL_PATERNITY_STATUS_KNOWN have issues, but we don't need
# them for linkage. Fix them later?

# List of invalid last names to filter out records later:
famlink_invalid_last <- c("UNK",
                          "UNKNOWN",
                          "UNKN",
                          "ZZPERSONUNKNOWN",
                          "KINDERCARE",
                          "DAYCARECENTER",
                          "VALLEYCHILDCARE",
                          "WSMC-HEADSTART",
                          "A CHILD'S",
                          "A KIDS WORLD",
                          "A PLACE CALLED HOPE",
                          "A PLACE FOR KIDS",
                          "A STEP AHEAD",
                          "AACRES WA LLC",
                          "ABC'S OF CHILD CARE",
                          "ABC CHILDRENS",
                          "ABC CHILDRENS CENTER",
                          "ABC EARLY LEARNING A",
                          "ABC LEARNING CENTER",
                          "ABC LEARNING CTR",
                          "ABC PRESCHOOL",
                          "ABC PRESCHOOL AND DC",
                          "ABERDEEN AREA",
                          "ACADEMY LITTLE BEARS",
                          "ACADEMY PRESCHOOL",
                          "ACADEMY SCHOOL",
                          "ACCRES WA LLC",
                          "ACHIEVEMENT CENTER",
                          "ACHIEVEMENT CTR PRES",
                          "ADOPTIVE PARENT",
                          "ADULT FEMALE",
                          "ADULT HH MEMBER",
                          "ADULT MALE",
                          "ADVENT LUTHERAN CCC",
                          "ADVENTURE KIDS",
                          "AGES IN STAGES",
                          "ALICES PRECIOUS JWLS",
                          "ALL HOURS DAY CARE",
                          "ALLEN CREEK ELEM",
                          "ALPHABET PRESCHOOL",
                          "ALPHABET SOUP",
                          "ALPINE HOUSE",
                          "ALTAMESE ACADEMY I",
                          "ALTAMESE ACADEMY II",
                          "AMARA EMERGENCY",
                          "AMAZING WORLD",
                          "AMBITIONS OF WA INC",
                          "ANNAS CHILDCARE",
                          "ANNAS PLAYHOUSE",
                          "ANOTHER BEST",
                          "ANOTHER BEST CC",
                          "ANY AND ALL PUTATIVE",
                          "ARISE AND SHINE",
                          "ARISE N SHINE",
                          "ARIZONA FATHER",
                          "ASHLEY HOUSE",
                          "AUBURN ADVENTIST",
                          "AUBURN DAYCARE",
                          "AUBURN MOTHER",
                          "AUNT BOYFRIEND",
                          "BABY ATOFAU",
                          "BABY BLISS",
                          "BACKSTRETCH CLUBHOUS",
                          "BALLARD BOYS GIRLS",
                          "BATES ERL CHLD LRN C",
                          "BATTLE GROUND",
                          "BATTLE GROUND GRACE",
                          "BEL RED BILINGUAL",
                          "BELLINGHAM MOM",
                          "BENTON CITY",
                          "BETHEL CHRISTIAN",
                          "BEYOND THE RAINBOW",
                          "BIBITY BOBITY",
                          "BILINGUAL LEARNING",
                          "BIOLOGICAL FATHER",
                          "BIRCH TREE ACADEMY",
                          "BLOSSOMING HILL MONT",
                          "BLOSSOMS EARLY",
                          "BLUE COMPASS CAMPS",
                          "BLUE PLATE",
                          "BOEING FAMILY CENTER",
                          "BONNEY LAKE",
                          "BOYFRIEND'S FATHER",
                          "BOYFRIEND OF",
                          "BOYFRIEND OF MOM",
                          "BOYFRIEND UNK",
                          "BOYFRIEND UNKNOWN",
                          "BOYS AND GIRLS",
                          "BOYS AND GIRLS CLUB",
                          "BOYS RANCH",
                          "BOYS SCOUTS OF",
                          "BREAKTHROUGH INC",
                          "BREAKTHROUGH SPOKANE",
                          "BREAKTHROUGH SUMAC",
                          "BREMERTON MOTHER",
                          "BREMERTON UNKNOWN",
                          "BRIARCREST ELEM",
                          "BRIDGEPORT CHILDCARE",
                          "BRIGHT BEGINNINGS",
                          "BRIGHT HORIZONS",
                          "BRIGHT HORIZONS WEST",
                          "BRITON HOUSE",
                          "BROOKLAKE CHILD CARE",
                          "BROWN UNBORN",
                          "BUILDING BLOCKS",
                          "BUILDING BLOCKS INC",
                          "BUSY BEAR DAYCARE",
                          "BUSY BODIES",
                          "BUZI BEE CHILD CARE",
                          "C AND C KIDS",
                          "C LOVER CHLD DEV CEN",
                          "CADENCE ACADEMY",
                          "CALIFORNIA UNKNOWN",
                          "CAMANO LUTHERAN",
                          "CAMELOT MOBILE HOME",
                          "CAMP FIRE USA",
                          "CAMP OUTLOOK",
                          "CAMP STEVE",
                          "CAMP YAVNEH",
                          "CANYON CREEK",
                          "CANYON VIEW",
                          "CARE BEAR CHILDCARE",
                          "CARING COMMUNITY",
                          "CARING CORNER",
                          "CARING HANDS LEARNIN",
                          "CAROUSEL CORNER",
                          "CARRATO VARELA",
                          "CASCADE CHRISTIAN",
                          "CASTLE ROCK",
                          "CCC AEC",
                          "CCS GRAYS HARBOR CNT",
                          "CDSA LAUNCH AT",
                          "CEDAR CREEK",
                          "CEDAR CREST ACADEMY",
                          "CEDAR HOUSE",
                          "CEDAR RIVER MONTESOR",
                          "CEDARBROOK DAYCARE",
                          "CELA'S CREATIVE",
                          "CENTER AT CENTRAL PA",
                          "CENTER FOR FAMLIES",
                          "CENTRAL YMCA CC",
                          "CENTRALIA COLLEGE",
                          "CENTRALIA SCHOOL",
                          "CHAMPION HOUSE",
                          "CHEHALIS AREA",
                          "CHEHALIS AVE",
                          "CHEHALIS AVENUE",
                          "CHERRY HILL MONTESSO",
                          "CHESTNUT MONTESSORI",
                          "CHI CHO OTSK ATI",
                          "CHICO CHRISTIAN",
                          "CHIL D",
                          "CHILD'S TIME INC",
                          "CHILD CARE AND SCHOO",
                          "CHILD DEV CTR",
                          "CHILD DEVELOPEMENT C",
                          "CHILD DEVELOPMENT",
                          "CHILD LEARN AND CARE",
                          "CHILD ONE",
                          "CHILD STUDY TRT CTR",
                          "CHILD TWO",
                          "CHILD UNBORN",
                          "CHILD VICTIM",
                          "CHILDCARE CENTER",
                          "CHILDREN'S ACADEMY",
                          "CHILDREN'S LEARNING",
                          "CHILDREN'S SOLA",
                          "CHILDREN'S VILLAGE",
                          "CHILDREN ACADEMY II",
                          "CHILDREN ARE SPECIAL",
                          "CHILDREN GOING INTO",
                          "CHILDREN OF HOPE",
                          "CHILDREN OF KAYLE",
                          "CHILDRENS ACADEMY",
                          "CHILDRENS CHARACTER",
                          "CHILDRENS COUNTRY",
                          "CHILDRENS DREAM",
                          "CHILDRENS HOME SOCIE",
                          "CHILDRENS HOSPITAL",
                          "CHILDRENS HS",
                          "CHILDRENS LEARNING",
                          "CHILDRENS LIFE III",
                          "CHILDRENS MONTESSORI",
                          "CHILDRENS SERV NW",
                          "CHILDRENS SERVICES",
                          "CHILDRENS VILLA",
                          "CHILDRENS VILLAGE",
                          "CHILDRENS VILLAGE CC",
                          "CHILDS TIME II",
                          "CHILDS TIME III",
                          "CHILDS TIME ONE",
                          "CHILDS TIME SIX",
                          "CHILDTIME LEARNING",
                          "CHINESE INFORMATION",
                          "CHRIST LUTHERAN",
                          "CHRIST LUTHERAN CC",
                          "CHRISTIAN FAITH",
                          "CHRISTINES LITTLE AT",
                          "CHURCH CHILD CARE",
                          "CIRCLE STREET",
                          "CITIZEN ACCESS",
                          "CLALLAM COUNTY",
                          "CLARK COLLEGE",
                          "CLARK COUNTY",
                          "CLEAR CREEK",
                          "CLYDE HILL",
                          "COCOON COMPLEX",
                          "COCOON HOUSE",
                          "COCOON HOUSE NORTH",
                          "COLLEGE FOR KIDS",
                          "COLORADO STREET",
                          "COMM CRISIS STABLIZA",
                          "COMM DAY SCHOOL",
                          "COMMUNITY CENTER",
                          "COMMUNITY CHILD CARE",
                          "COMMUNITY DAY SCHOOL",
                          "COMMUNITY FACILITY",
                          "COMMUNITY HOUSE",
                          "COOKS HILL CCC",
                          "COOP PRESCHOOL",
                          "COTTESMORE CCC",
                          "COTTESMORE CDC",
                          "COUNTRY CAMPUS",
                          "COUNTRY DAWN",
                          "COUNTRY KIDS",
                          "COUNTY III",
                          "COUSIN ONE",
                          "COUSIN TWO",
                          "COUSINS ROAD",
                          "COWLITZ COUNTY",
                          "CRAYON COLLEGE",
                          "CREATIVE ADVENTURES",
                          "CREATIVE DISCOVERY",
                          "CREATIVE KIDS",
                          "CREATIVE MONTESSORI",
                          "CREATIVE SPROUTS",
                          "CRISIS RESIDENTIAL",
                          "CURIOSITY CORNER",
                          "CYPRESS HOUSE",
                          "CYS -NEW DIRECTIONS",
                          "DAD'S GIRLFRIEND",
                          "DAD OF NICKO",
                          "DALE TURNER YMCA",
                          "DAUGHTER OF",
                          "DAY CARE",
                          "DAYCARE AND LEARNING",
                          "DAYCARE DEVINE",
                          "DAYCARE STAFF",
                          "DAYCARE WORKER",
                          "DDA GROUP HOME",
                          "DEER LAKE GIRLS HOME",
                          "DELAWARE ST LONGVIEW",
                          "DETENTION STAFF",
                          "DISCOVERY DEPOT",
                          "DISCOVERY LAND",
                          "DISCOVERY STATION",
                          "DREAMKIDZ ACADEMY",
                          "DRY CREEK",
                          "DUAL LANGUAGE",
                          "DUCK DUCK GOOSE",
                          "DUPONT LEARNING CTR",
                          "EAGLE CREEK ELEM",
                          "EARLY BIRD DAYCARE",
                          "EARLY BLOOMERS",
                          "EARLY LEARNING",
                          "EARLY LEARNING ACADE",
                          "EARLY LEARNING CTR",
                          "EARLY WORLD CHILDREN",
                          "EASTER SEALS",
                          "EASTER SEALS NE CC",
                          "EASTSIDE CHRISTIAN",
                          "EATONVILLE ELC",
                          "ECCC EARLY HEADSTART",
                          "ECHO GLEN",
                          "ECHO GLEN STAFF",
                          "EDUCARE EARLY",
                          "EDUCARE EARLY LEARN",
                          "EDUCATION CENTER",
                          "ELEMENTARY SCHOOL",
                          "ELITE KIDS",
                          "ELK PLAIN SCHOOL",
                          "EMBASSY EDUCATIONAL",
                          "EMMANUEL LUTHERAN",
                          "EMMANUEL LUTHERAN DC",
                          "ENCHANTED LITTLE",
                          "ENSIGN RANCH",
                          "EOCF ELLSWORTH SITE",
                          "EOCF NINETY NINE",
                          "ETON SCHOOL",
                          "EUROPAKIDS INTERNATI",
                          "EVERETT BOYS GIRLS",
                          "EVERETT CHILDREN",
                          "EVERETT FAMILIES",
                          "EVERETT MOM",
                          "EVERGREEN ACADEMY DA",
                          "EVERGREEN MANOR",
                          "EVERGREEN SCHOOL",
                          "EX PARTNER",
                          "EXCEL SL INC",
                          "EXCEL SUP LIVING TWO",
                          "EXCEL SUPPORTED",
                          "EXCELSIOR YOUTH GH",
                          "EYAS GLOBAL",
                          "FAIRFAX HOSPITAL",
                          "FAIRMOUNT VANCOUVER",
                          "FAITH FAMILY CC",
                          "FAITH LUTHERAN",
                          "FAMILY CIRCLE",
                          "FAMILY GROWTH CENTER",
                          "FAMILY MEMBER",
                          "FAMILY MEMBER PARENT",
                          "FARWELL ELEMENTARY",
                          "FATHER'S WIFE",
                          "FATHER FIGURE",
                          "FATHER IN OR",
                          "FATHER OF",
                          "FATHER OF KIERA",
                          "FECHENBACH SR",
                          "FEDERAL WAY BOYS",
                          "FEDERAL WAY DAD",
                          "FEMALE CHILD",
                          "FEMALE COUNSELOR",
                          "FEMALE STAFF",
                          "FEMALE VICTIM",
                          "FIANCEE OF",
                          "FIFTEEN CHILDREN",
                          "FIFTEEN YEAR OLD BOY",
                          "FIRST LEARNING TREE",
                          "FIRST STEPS",
                          "FIRST STEPS ACADEMY",
                          "FIRST STEPS CDC",
                          "FIRST STEPS CDC II",
                          "FIRST UNITED METH",
                          "FIVE YEAR OLD",
                          "FLORES MARTINEZ",
                          "FOOTHILLS LEARNING",
                          "FOOTPRINTS CHILD",
                          "FOREST FRIENDS",
                          "FOSTER CHILD",
                          "FOSTER CREEK RD RV",
                          "FOSTER CREEK RV",
                          "FOSTER FATHER",
                          "FOSTER MOTHER",
                          "FOSTER PARENT",
                          "FOUR CHILDREN",
                          "FOUR FREEDOMS",
                          "FOURSQUARE CHURCH",
                          "FOURTH PLAIN PLAZA",
                          "FRENCH AMERICAN",
                          "FRIENDS OF YOUTH",
                          "FRIENDS UNCLE",
                          "FROM ROOTS TO WINGS",
                          "FULTZ UNBORN",
                          "FUN TIMES DAYCARE",
                          "FUN TO LEARN",
                          "FUTURE TRUST",
                          "GARNERO CHILD DEV",
                          "GATEWAY CHRISTIAN CC",
                          "GEARABY GEARS",
                          "GENESEE EARLY",
                          "GENESIS HOUSE",
                          "GIGGLING CHILDCARE",
                          "GIGGLING GUEST AGAIN",
                          "GIGGLING GUEST CC",
                          "GILMAN CHILD CARE",
                          "GINGERBREAD HOUSE",
                          "GIRLS HOME",
                          "GIVING TREE LEARNING",
                          "GLASS POND",
                          "GLEN ECHO",
                          "GOD DAD",
                          "GODDARD SCHOOL",
                          "GOLDEN RULE",
                          "GRACE CARE",
                          "GRACE CHILDRENS CENT",
                          "GRAHAM HILL KID",
                          "GRAMMIS HOUSE",
                          "GRANDFATHER UNKNOWN",
                          "GREAT BEGINNINGS",
                          "GREAT BEGINNINGS II",
                          "GREAT KIDS ACADEMY",
                          "GREATER TRINITY",
                          "GREEN ACRES",
                          "GREEN ACRES LEARNING",
                          "GREEN GABLE NORTH",
                          "GREEN RIVER",
                          "GREEN RIVER COMM COL",
                          "GREEN RIVER RIDGE",
                          "GREENLAKE SCH-AGE",
                          "GROUP HOME",
                          "GROW WITH US",
                          "GROW WITH US INC",
                          "GROWING HOPE CHILD",
                          "GROWING SMART KID'Z",
                          "GUARDIAN ANGELS CC",
                          "HAMBLEN EXPRESS",
                          "HAPPY DAYS DAY CARE",
                          "HAPPY HARTS CLD CARE",
                          "HASELWOOD YMCA",
                          "HAVEN HOUSE",
                          "HAYES CHILD DEV CTR",
                          "HEAD START",
                          "HEAVENLY PLACE DAYCA",
                          "HELPING HANDS",
                          "HELPING HANDS ELGIN",
                          "HERITAGE UNIVERSITY",
                          "HIAWATHA COMMUNITY",
                          "HIGH SCHOOL",
                          "HIGHLAND COMM CNTR",
                          "HIGHLAND PARK",
                          "HILLSIDE CDC",
                          "HISPANIC CHILDREN",
                          "HISPANIC MALE",
                          "HOME CARE",
                          "HOME CARE PROVIDER",
                          "HOME ZONE",
                          "HONDURAS SOLDIERS",
                          "HOPEFUL HANDS",
                          "HOPKINS UNBORN",
                          "HOSPITAL STAFF",
                          "HOUSING FOUNDATION",
                          "HUDSON MANOR",
                          "HUGS TUGS N LUV I",
                          "HUTTON SETTLEMENT",
                          "ID BABYSITTER",
                          "IMAGINATION STATION",
                          "IMMANUEL PRESCHOOL",
                          "IN HIS HANDS LRN CTR",
                          "INNOVATIVE SERVICE",
                          "INNOVATIVE SERVICES",
                          "INSPIRE DEV I",
                          "INSPIRE DEVELOPMENT",
                          "INSPIRE DEVELPMENT",
                          "INTERIM HEALTHCARE",
                          "INTERLAKE CHILDCARE",
                          "INTERNATIONAL SCHOOL",
                          "IS NOT KNOWN",
                          "J STREET TRANSITION",
                          "JACK AND JILL",
                          "JACKSON PARK CDC",
                          "JEALOUS OF HIM",
                          "JEFFERSON CCC",
                          "JESSICA'S PARTNER",
                          "JITTERBUG CHILD CARE",
                          "JIVE AFTER SCHOOL",
                          "JOURNEYS MONTESSORI",
                          "JOYFUL NOISE",
                          "JUBILEE LEADERSHIP",
                          "JUMP FOR JOY TOO",
                          "JUST FOR KICKS",
                          "JUST FOUR KIDS INC",
                          "JUST IMAGINE",
                          "JUST LIKE HOME",
                          "KALER HOUSE",
                          "KELLY LAKE MONTESSOR",
                          "KELSO CHRISTIAN",
                          "KENNEWICK CHRISTIAN",
                          "KENT COVENANT",
                          "KENT VALLEY EARLY",
                          "KID'S COUNTRY PRESCH",
                          "KID CENTRAL",
                          "KID KARE DAYKARE INC",
                          "KID SAFARI",
                          "KIDDIE ACADEMY",
                          "KIDDY KORNER",
                          "KIDS AT HEART",
                          "KIDS CITY",
                          "KIDS CLUB",
                          "KIDS CO",
                          "KIDS CO MCDONALD",
                          "KIDS COMPANY",
                          "KIDS CORNER",
                          "KIDS COUNTRY",
                          "KIDS COUNTRY INC",
                          "KIDS COUNTRY MONROE",
                          "KIDS FIRST CHILD CNT",
                          "KIDS IN THE",
                          "KIDS KAMPUS",
                          "KIDS KORNER",
                          "KIDS KORNER V",
                          "KIDS KREW AT TERRACE",
                          "KIDS N ME",
                          "KIDS N PLAY",
                          "KIDS N US",
                          "KIDS N US INC",
                          "KIDS R NINOS",
                          "KIDS R SPECIAL",
                          "KIDS WORLD",
                          "KIDS WORLD BLDG A",
                          "KIDS WORLD BLDG B",
                          "KIDS WORLD FERNDALE",
                          "KIDS WORLD NW",
                          "KIDSPACE INC",
                          "KIDZ C",
                          "KIDZLE B KIDS",
                          "KIDZONE LEARNING CT",
                          "KIDZONE LEARNING CTR",
                          "KINDER CARE",
                          "KINDER KAMPUS",
                          "KINDERCARE - REDONDO",
                          "KINDERCARE EGHTFIVON",
                          "KINDERCARE FVNINEO",
                          "KINDERCARE HARBORPT",
                          "KINDERCARE ISSAQUAH",
                          "KINDERCARE LEARNING",
                          "KINDERCARE NORTHGATE",
                          "KINDERCARE ONEFRSEVN",
                          "KINDERCARE ONETHROFV",
                          "KINDERCARE OVERLAKE",
                          "KINDERCARE WEST OLY",
                          "KINDERHAFEN LLC",
                          "KINDERLAND ACAD LG",
                          "KING COUNTY",
                          "KING OSCAR MOTEL",
                          "KINGS WAY LEARNING",
                          "KITSAP CHILD CARE",
                          "KITSAP MENTAL HEALTH",
                          "KLA OF BELLEVUE",
                          "KNOWLEDGE KOLLEGE",
                          "KNOWLEDGE LEARNING",
                          "KRE A TIVE-KIDZ",
                          "KREATIVE KIDZ C",
                          "KREATIVE KIDZ O",
                          "LA ESCUELITA",
                          "LA FITNESS",
                          "LA PETITE ACADEMY",
                          "LACEY HOUSE",
                          "LACEY LEARNING CENTE",
                          "LACEY LEARNING LLC",
                          "LADDERS OF LOVE",
                          "LAKE FOREST PARK",
                          "LAKE FOREST PARK MON",
                          "LAKE HEIGHTS YMCA",
                          "LAKE HILLS EARLY",
                          "LAKE SAWYER HOUSE",
                          "LAKE STEVENS CHRIST",
                          "LAKE STEVENS DAYCARE",
                          "LAKE STEVENS MOM",
                          "LAKE TAPPS CHRISTIAN",
                          "LAKELAND VILLAGE",
                          "LAKESIDE MONTESSORI",
                          "LAKEVIEW DAY",
                          "LAKEVIEW ELEMENTARY",
                          "LANGUAGE GARDEN",
                          "LAPETITE-GEM HEIGHTS",
                          "LAPETITE ACADEMY",
                          "LARSEN BABY",
                          "LASER AT BRYANT ELEM",
                          "LAST NAME UNKNOWN",
                          "LCC HEAD START",
                          "LEAP AHEAD CHILD DEV",
                          "LEARNING ADVENTURES",
                          "LEARNING AVENUES",
                          "LEARNING CENTER",
                          "LEARNING LADDER",
                          "LEARNING LAND",
                          "LEARNING LAND TWO",
                          "LEARNING TO GROW",
                          "LEARNING TREE",
                          "LEARNING WAY",
                          "LEGAL GUARDIAN",
                          "LEGENDS CASINO EMP",
                          "LEWIS COUNTY",
                          "LIBERTY LAKE",
                          "LIGHTHOUSE II",
                          "LIGHTHOUSE III",
                          "LIGHTHOUSE IV",
                          "LIGHTHOUSE SIX",
                          "LIGHTHOUSE V",
                          "LIGHTHOUSE VI",
                          "LIGHTHOUSE VII",
                          "LIGHTHOUSE VIII",
                          "LIL' SPROUTS LRN CTR",
                          "LIL CHIEFS",
                          "LIL CHIEFS CCC",
                          "LIL HAWKS",
                          "LIL KIDS N ME CHILD",
                          "LIL PEOPLE WORLD",
                          "LIL PEOPLES",
                          "LIL PEOPLES II",
                          "LIL PEOPLES III",
                          "LIL PEOPLES WORLD",
                          "LINCOLN HEIGHTS EXPR",
                          "LISA'S DAYCARE",
                          "LITTLE ANGEL",
                          "LITTLE AVIATORS",
                          "LITTLE BRAVE",
                          "LITTLE DICKENS LEARN",
                          "LITTLE DOVES",
                          "LITTLE DREAMERS",
                          "LITTLE FOREST",
                          "LITTLE INSPIRATIONS",
                          "LITTLE LAKE HOUSE",
                          "LITTLE LAMBS",
                          "LITTLE LAMBS CHILD",
                          "LITTLE LAURELS",
                          "LITTLE LEARNER",
                          "LITTLE LEARNER'S",
                          "LITTLE LEARNER DEV",
                          "LITTLE LEARNERS CDC",
                          "LITTLE LEGENDS CCC",
                          "LITTLE LIONS DAYCARE",
                          "LITTLE PEOPLE'S",
                          "LITTLE RASCALS",
                          "LITTLE SAFARI CC",
                          "LITTLE SCHOLARS",
                          "LITTLE SCHOLARS ELC",
                          "LITTLE SQUIRTS",
                          "LITTLE SUNSHINE LC",
                          "LITTLE TIGERS",
                          "LITTLE VILLAGE",
                          "LIVING MONTESSORI",
                          "LONGVIEW FLEEING",
                          "LONGVIEW NEIGBOR",
                          "LONGVIEW RESIDENT",
                          "LONGVIEW SON",
                          "LONGVIEW UNKNOWN",
                          "LOVE AND KINDNESS",
                          "LOVE AND LEARN",
                          "LOVE N LAUGHTER LRN",
                          "LTL CHRCH ON PRAIRIE",
                          "LTL CHURCH PRAIRIE",
                          "LUMMI CHILD CARE",
                          "LUMMI YOUTH",
                          "LYNNWOOD MALE",
                          "MAGIC LANTERN",
                          "MAGNOLIA WHIZZ KIDS",
                          "MALE BABYSITTER",
                          "MALE CHILD",
                          "MALE FRIEND",
                          "MALE SIBLING",
                          "MALE STAFF",
                          "MALE STAFF MEMBER",
                          "MALE UNKNOWN",
                          "MAPLE LANE SCHOOL",
                          "MAPLE LANE UNKNOWN",
                          "MAPLE STREET",
                          "MARTHA AND MARY",
                          "MARTIN LUTHER KING J",
                          "MARYSVILLE CHILDREN",
                          "MARYSVILLE DAY CARE",
                          "MARYSVILLE DAYCARE",
                          "MARYSVILLE MOTHER",
                          "MASON COUNTY",
                          "MATERNAL AUNT",
                          "MCBEE LEARNING",
                          "MEAD HIGH",
                          "MEADOW WOOD CC",
                          "MENDOZA BABY",
                          "MEXICAN STORE OWNER",
                          "MIDLANDS KIDDIE KORR",
                          "MILAM STAFF",
                          "MILGARD CHILD DEVEL",
                          "MILL CREEK YMCA",
                          "MILLENIUM KIDS",
                          "MILLENNIUM KIDS",
                          "MILLER BABY",
                          "MILLER O'HIGGINS",
                          "MINI SKOOL",
                          "MINI SKOOL EARLY LRN",
                          "MINNEHAHA EARLY",
                          "MINOR AGE COUSIN",
                          "MINT PLACE LONGVIEW",
                          "MISS AMY",
                          "MOMS BOYFRIEND",
                          "MOMS COMMUNITY CCC",
                          "MONKEYN AROUND",
                          "MONTESSORI SCHOOLS",
                          "MORE SMILES LRN CTR",
                          "MORNING STAFF",
                          "MORNING STAR BOSCO",
                          "MORNING STAR RANCH",
                          "MOTEL SIX EAST",
                          "MOTHER'S BOYFRIEND",
                          "MOTHER'S PARTNER",
                          "MOTHER BOYFRIEND",
                          "MOTHER HUBBARD",
                          "MOTHER OF",
                          "MOTHER UNKNOWN",
                          "MOUNT VERNON",
                          "MOUNTAINEERS CLUB",
                          "MOUNTAINSIDE SCHOOL",
                          "MT OLIVE EVANGELICAL",
                          "MT VERNON KIDS N US",
                          "MUCKLESHOOT CLD DEV",
                          "MULTICULT CLD N FAM",
                          "MULTIPLE CHILDREN",
                          "MULTIPLE VICTIMS",
                          "MUNCHKINLAND I",
                          "MUSTARD SEED HS",
                          "MY BROTHERS KEEPER",
                          "MY FRIENDS",
                          "MY SCHOOL PRESCHOOL",
                          "NAME UNKNOWN",
                          "NAMES UNKNOWN",
                          "NASELLE YOUTH CAMP",
                          "NATURE NURTURES FARM",
                          "NAVY SCHOOL AGE CARE",
                          "NEIGHBOR BOY",
                          "NEVERLAND CHILDCARE",
                          "NEW BORN",
                          "NEW HORIZONS",
                          "NEW JERUSALEM",
                          "NEW MEXICO",
                          "NEW VISION PROG INC",
                          "NEW VISIONS",
                          "NEW VISIONS PROG INC",
                          "NEWPORT CHILD PRESCH",
                          "NIGHT OWL DC",
                          "NO LAST NAME",
                          "NOAH'S ARK",
                          "NOAH'S ARK EARLY LEA",
                          "NORTH AVENUE EARLY",
                          "NORTH DAY CAMP",
                          "NORTH FORT",
                          "NORTH FORT YOUTH CTR",
                          "NORTH FOURTH",
                          "NORTH LAKE DAD OR BF",
                          "NORTH LAKE STUDENT",
                          "NORTH MONROE DAYCARE",
                          "NORTH SEATTLE",
                          "NORTH TACOMA MONTESO",
                          "NORTH THURSTON",
                          "NORTHEAST CHILD",
                          "NORTHEAST TACOMA",
                          "NORTHGATE COMMUNITY",
                          "NORTHGATE EARLY",
                          "NORTHGATE ELEMENTARY",
                          "NORTHLAKE PRESCHOOL",
                          "NORTHSHORE MONTESSOR",
                          "NORTHWEST CENTER",
                          "NORTHWEST CHILDREN'S",
                          "NORTHWEST CHRISTIAN",
                          "NORTHWEST CTR KIDS",
                          "NOT KNOWN",
                          "NOT KNOWN NAME",
                          "NOTCHLOG DRIVE",
                          "NOTCHLOG DRIVE VANC",
                          "NW CHILDREN'S HOME",
                          "OAK BRIDGE SHELTER",
                          "OAKBROOK CHILDRENS",
                          "OAKRIDGE COMMUNITY",
                          "OAKRIDGE MONTESSORI",
                          "OCEAN SHORES",
                          "OF EX-GIRLFRIEND",
                          "OHANA CRISIS CENTER",
                          "OLYMPIA UNKNOWN",
                          "OLYMPIC VIEW",
                          "OMAS PLAYHOUSE",
                          "ONALASKA UNKNOWN",
                          "OREGON DAYCARE",
                          "OTHER ORGANIZED",
                          "OUR BEGINNING",
                          "OUR NEXT",
                          "OUR NEXT GENERATION",
                          "OUR PLACE TO GROW",
                          "OVERLAKE SPECIALITY",
                          "PANDA BEAR CC",
                          "PARAMOUNT CHRISTIAN",
                          "PARENT A",
                          "PARENT B",
                          "PARENT OF",
                          "PARKVIEW EARLY LC",
                          "PASCO SCHOOL",
                          "PAST BOYFRIEND",
                          "PATERNAL RELATIVE",
                          "PAVILION KIDS KREW",
                          "PAVLISH PLAYHOUSE",
                          "PEACE OF MIND",
                          "PEARL STREET",
                          "PEARL STREET PROGRAM",
                          "PEDIATRIC INT CARE",
                          "PENINSULA CHURCH",
                          "PERINATAL TREATMENT",
                          "PERSON UNKNOWN",
                          "PETITE DAY CARE",
                          "PHINNEY NEIGHBORHOOD",
                          "PIONEER HUMAN SERVIC",
                          "PIONEER HUMAN SVCS",
                          "PIONEER PRESCHOOL",
                          "PIONEER RECEIVING",
                          "PLACE PRESCHOOL",
                          "PLANET KIDS",
                          "PLANET KIDS INC",
                          "PNA ENRICHMENT PROG",
                          "PNW HELPING HANDS",
                          "POPES KIDS PLACE INC",
                          "PORT ANGELES UNKNOWN",
                          "PORT GAMBLE",
                          "POSITIVE DIRECTIONS",
                          "POSSIBLE DAY CARE",
                          "POST ALLEY KIDS CNTR",
                          "PRECIOUS ANGELS",
                          "PRECIOUS BLESSINGS",
                          "PRECIOUS CHILD CARE",
                          "PRECIOUS TIMES",
                          "PRIMM TABERNACLE",
                          "PROMISE COMMUNITY",
                          "PROSPECT ENRICHMENT",
                          "PUBLIC SCHOOL",
                          "PUGET SOUND LUTHERAN",
                          "PUYALLUP LEARNING",
                          "PUYALLUP MOTHER",
                          "PUYALLUP PLAYCARE CT",
                          "RAD SERVICE ALT",
                          "RAINBOW CHILD CARE C",
                          "RAINBOW CONNECTION",
                          "RAINBOW CONNECTION T",
                          "RAINBOW CONNECTIONS",
                          "RAINBOW KIDS THREE",
                          "RAINBOWS END",
                          "RAINBOWS END NORTH",
                          "RAINIER CHRISTIAN",
                          "RAINIER COMMUNITY",
                          "RAINIER STUDENT",
                          "RAINIER VISTA-ECEAP",
                          "RAMTHA'S SCHOOL OF",
                          "RAY OF HOPE",
                          "RECOVERY CENTER",
                          "REGINALIN'S PARTNER",
                          "RENTON SKY WAY",
                          "RENTON TECHNICAL COL",
                          "RESTAURANT FATHER",
                          "RIGHT AT SCHOOL",
                          "ROBYNS NEST",
                          "ROCK CREEK",
                          "ROOT ACADEMY",
                          "ROYAL FAMILY KIDS",
                          "ROYAL PALACE",
                          "RUTH DYKEMAN",
                          "RUTH DYKEMAN - NAVOS",
                          "RUTH DYKEMAN CHILD",
                          "RYTHER CHILD CENTER",
                          "SACRED HEART",
                          "SAFE HARBOR",
                          "SALISH SCHOOL OF",
                          "SALLYS HOUSE",
                          "SALMON CREEK",
                          "SAMMAMISH CHILDRENS",
                          "SCHOOL AGED CHILD",
                          "SCHOOL BUS DRIVER",
                          "SCHOOL DISTRICT",
                          "SCHOOL KIDS CLUBHOUS",
                          "SCHOOL STAFF",
                          "SEA MAR CHILD DEV",
                          "SEADRUNAR DAYCARE",
                          "SEATTLE CHILDRENS",
                          "SEATTLE LEARNING",
                          "SEATTLE SCHOOL",
                          "SECRET HARBOR",
                          "SEED OF LIFE",
                          "SEQUIM UNKNOWN",
                          "SEQUOIA'S TREEHOUSE",
                          "SERENDIPITY ACADEMY",
                          "SERENITY RESIDENTIAL",
                          "SERVICE ALTERNATIVES",
                          "SERVICES NW CCC",
                          "SEVEN YEAR OLD",
                          "SEVENTH DAY",
                          "SHELTON VALLEY",
                          "SHILOH HILLS",
                          "SHORELINE CHRISTIAN",
                          "SHORELINE COMM COLL",
                          "SIBLING A",
                          "SIBLING B",
                          "SIERRA DRIVE KELSO",
                          "SILVER LAKE CCC",
                          "SIX YEAR OLD",
                          "SKAGIT VALLEY",
                          "SKAGIT VALLEY YMCA",
                          "SL START",
                          "SL START-FIVE",
                          "SL START-FOUR",
                          "SL START HIGHLAND",
                          "SL START RICHMOND",
                          "SL START SHERWOOD",
                          "SL START SOUNDVIEW",
                          "SMALL DIMENSIONS DAY",
                          "SMALL DIMENSIONS II",
                          "SMALL FACES",
                          "SMALL WONDERS",
                          "SMALL WONDERS CCC",
                          "SMALL WONDERS CHILD",
                          "SMALL WONDERS TOO",
                          "SMALL WORLD CHILD",
                          "SMART START",
                          "SMITHWRIGHT OLYMPIC",
                          "SMITHWRIGHT SERVICES",
                          "SMITHWRIGHT WILLOW",
                          "SMOKEY POINT DAYCARE",
                          "SMOKEY PT",
                          "SMR SHORELINE",
                          "SO SOUND YMCA",
                          "SOCIAL WORKER",
                          "SONSHINE CHRISTIAN",
                          "SONSHINE LEARNING CE",
                          "SOPHIA BREMER CDC",
                          "SOUND MENTAL HEALTH",
                          "SOUND TO HARBOR ELP",
                          "SOUTH KING CO YOUTH",
                          "SOUTH KITSAP",
                          "SOUTH PARK COMM CTR",
                          "SOUTH SHORE",
                          "SPANAWAY LUTHERAN CH",
                          "SPOKANE CHILD",
                          "SPOKANE COUNTY",
                          "SPOKANE DAD",
                          "SPOKANE MOM",
                          "SPOKANE PARENT",
                          "SPRING GLEN",
                          "SPRING GLEN ACADEMY",
                          "SPRINGTIME DAY CARE",
                          "SPROUTS GROWTH CTR",
                          "SPROUTS GRTH CTR II",
                          "SPRUCE ST",
                          "SPRUCE STREET SCRC",
                          "SPSCC YMCA",
                          "SQUAXIN ISLAND CDC",
                          "SS YMCA BLACK LAKE",
                          "ST ANNES",
                          "ST ANNES CHILDRENS",
                          "ST JOHN S EXTENDED",
                          "ST LUKE'S CHILDCARE",
                          "ST MIKES TIKES",
                          "ST PATRICK CHILDCARE",
                          "STAFF MEMBER",
                          "STAFF PERSON",
                          "STAFF SPRUCE ST",
                          "STAFF YMCA--JACKSON",
                          "STAFFORD ELEMENTARY",
                          "STARS OF ABRAHAM",
                          "STEP BROTHER",
                          "STEP DAD",
                          "STEP FATHER",
                          "STEPPING STONE",
                          "STEPPING STONES",
                          "STEPPING STONES CC",
                          "STEVENSON CC",
                          "STEVENSON CHILDCARE",
                          "STROUM JEWISH",
                          "STROUM JEWISH COMMUN",
                          "SUBJECT TACOMA",
                          "SUMNER VALLEY PRE",
                          "SUNDANCE CHILD DEVEL",
                          "SUNDANCE PRESCHOOL",
                          "SUNDOWN M RANCH",
                          "SUNNY DAWN CC",
                          "SUNNYSIDE PRESCHOOL",
                          "SUNRISE COMM CTR",
                          "SUNRISE DAY CARE CTR",
                          "SUNRISE OUTREACH",
                          "SUNRISE SERVICES",
                          "SUQUAMISH TRIBAL",
                          "SWCCC IMAGE",
                          "SWCCC UNIONRIDGE CCC",
                          "SYLVAN WAY",
                          "SYLVAN WAY CHRISTIAN",
                          "SYLVESTER HOUSE",
                          "TACOMA DAYCARE",
                          "TACOMA FATHER",
                          "TACOMA MOTHER",
                          "TACOMA UNKNOWN",
                          "TAYLOR TOTS DAYCARE",
                          "TAYLOR TOTS TOO",
                          "TEACHERS CHILD CARE",
                          "TEN YEAR OLD",
                          "TENDER HEART",
                          "TENDER MOMENTS",
                          "TENDER YEARS",
                          "TENDER YEARS ACADEMY",
                          "TENNESSEE DAD",
                          "THE BABYSITTER",
                          "THE CHILD CARE",
                          "THE DAYCARE",
                          "THE FIRS BIBLE",
                          "THE FITNESS CENTER",
                          "THE GODDARD SCHOOL",
                          "THE LEARNING CENTER",
                          "THE LITTLE BEANS",
                          "THE LITTLE COMPANY",
                          "THE MERMAIDS LAGOON",
                          "THE RAINBOW SCHOOL",
                          "THIRTYNINTH STREET",
                          "THREE BEAR EDUCARE",
                          "THREE CEDARS SCHOOL",
                          "THREE TREE MONTESSOR",
                          "THRIZE FITNESS",
                          "TINY TOTS",
                          "TINY TOTS CENTER ONE",
                          "TINY TOTS DEV CTR",
                          "TODDLE TIMES",
                          "TODDLER TECH",
                          "TODDLER TOWN USA",
                          "TODDLERS UNIV FOUR",
                          "TODDLERS UNIVERSITY",
                          "TOLEDO UNKNOWN",
                          "TOMORROWS FUTURE INC",
                          "TOMORROWS HOPE",
                          "TOPS KIDS COMPANY",
                          "TREEHOUSE LLC",
                          "TREETOP VILLAGE",
                          "TRINITY LUTHERAN",
                          "TULALIP TRIBES CHILD",
                          "TWELVE YEAR OLD",
                          "TWENTIETH AVENUE",
                          "TWENTY FOUR HOUR",
                          "TWIN LAKES",
                          "TWIN RIVERS",
                          "TWO RIVERS LANDING",
                          "TWO YEARS TWO MONTHS",
                          "UKNOWN BROWN",
                          "UN KNOWN",
                          "UNBORN BABY",
                          "UNBORN BAUGHMAN",
                          "UNBORN CHILD",
                          "UNBORN PUYALLUP",
                          "UNION WAY KELSO",
                          "UNITED METHODIST",
                          "UNITY CHILDRENS UNIV",
                          "UNK NOWN",
                          "UNKN OWN",
                          "UNKNOWN ADULT",
                          "UNKNOWN ADULT MALE",
                          "UNKNOWN ASSAILANT",
                          "UNKNOWN BABYSITTER",
                          "UNKNOWN BISHOPROAD",
                          "UNKNOWN BOYFRIEND",
                          "UNKNOWN C",
                          "UNKNOWN CASTLE ROCK",
                          "UNKNOWN CENTRALIA",
                          "UNKNOWN CHEHALIS",
                          "UNKNOWN CHILD",
                          "UNKNOWN CHILD OF",
                          "UNKNOWN CHILDREN",
                          "UNKNOWN CO-WORKER",
                          "UNKNOWN COUSIN",
                          "UNKNOWN COUSIN'S",
                          "UNKNOWN COWLITZ",
                          "UNKNOWN DAUGHTER",
                          "UNKNOWN DRIVER",
                          "UNKNOWN EXCHANGE",
                          "UNKNOWN FATHER",
                          "UNKNOWN FEMALE",
                          "UNKNOWN FORLORN",
                          "UNKNOWN GIRLFRIEND",
                          "UNKNOWN GRANDFATHER",
                          "UNKNOWN HUSBAND",
                          "UNKNOWN INFANT",
                          "UNKNOWN KELSO",
                          "UNKNOWN LAKEWOOD",
                          "UNKNOWN LAST NAME",
                          "UNKNOWN LIGHTHOUSE",
                          "UNKNOWN LONGVIEW",
                          "UNKNOWN MALE",
                          "UNKNOWN MAN",
                          "UNKNOWN MOM",
                          "UNKNOWN MONROE HS",
                          "UNKNOWN MOTHER",
                          "UNKNOWN MOTHER'S",
                          "UNKNOWN MOTHER OF",
                          "UNKNOWN NAME",
                          "UNKNOWN NIEMI RD",
                          "UNKNOWN OREGON",
                          "UNKNOWN PARENT",
                          "UNKNOWN PARENT OF",
                          "UNKNOWN PARTNER",
                          "UNKNOWN PASSENGER",
                          "UNKNOWN PERPETRATOR",
                          "UNKNOWN PERSON",
                          "UNKNOWN PORT",
                          "UNKNOWN Q",
                          "UNKNOWN RANDLE",
                          "UNKNOWN ROOMMATE",
                          "UNKNOWN RUSSIAN",
                          "UNKNOWN RV",
                          "UNKNOWN SEAVIEW",
                          "UNKNOWN SKOKOMISH",
                          "UNKNOWN SPOKANE",
                          "UNKNOWN STAFF",
                          "UNKNOWN STEPDAD",
                          "UNKNOWN STEPFATHER",
                          "UNKNOWN STUDENT",
                          "UNKNOWN SUBJECT",
                          "UNKNOWN TACOMA",
                          "UNKNOWN TODDLER",
                          "UNKNOWN TUMWATER",
                          "UNKNOWN UNCLE",
                          "UNKNOWN UNKNOWN",
                          "UNKNOWN VANCOUVER",
                          "UNKNOWN WINLOCK",
                          "UNKNOWN WOODLAND",
                          "UNKNOWN YACOLT",
                          "UNKNOWNBATTLE GROUND",
                          "UNKNOWNFLORIDA STREE",
                          "URBAN FITNESS",
                          "URBAN IMPACT AT RAIN",
                          "UW CHILD CTR RADFORD",
                          "VALENCIA DRIVE VANC",
                          "VALLEY CHRISTIAN",
                          "VALLEY MED CENTER",
                          "VALLEY POINTE ECLC",
                          "VALUED KIDS",
                          "VANCOUVER AREA",
                          "VANCOUVER CHILD",
                          "VANCOUVER DAD",
                          "VANCOUVER MOM",
                          "VANCOUVER MOTHER",
                          "VANCOUVER UNKNOWN",
                          "VIRGINIA MILLER",
                          "VIRGINIA MILLER HOUS",
                          "VIRGINIA MILLER INC",
                          "VISION FOR NEW",
                          "VISIONS TWO",
                          "VISITATION PROGRAM",
                          "VISITING MOM",
                          "WA SCHOOL",
                          "WA STATE UNIVERSITY",
                          "WALDORF SCHOOL",
                          "WALNUT LANDING VANC",
                          "WARNER ST DAY CARE",
                          "WASHINGTON INTL",
                          "WASHINGTON WAY",
                          "WASHOUGAL AREA",
                          "WE LOVE LEARNING",
                          "WEDGEWOOD ELEMENTARY",
                          "WEDGWOOD KIDS TIME",
                          "WEE ARE THE WORLD",
                          "WEE CARE",
                          "WEE CARE DAY CARE",
                          "WEE CARE DAYCARE",
                          "WEE LOVE LEARNING",
                          "WELLSPRING FAMILY SE",
                          "WELLSPRING LEARNIN C",
                          "WEST BREMERTON",
                          "WEST CENTRAL COMMUNI",
                          "WEST HILL ELEMENTARY",
                          "WEST HWY",
                          "WESY HWY",
                          "WHIDBY AVENUE",
                          "WILDERNESS THERAPY",
                          "WONDER KIDS",
                          "WONDER YEARS",
                          "WOODIN ELEMENTARY",
                          "WOODINVILLE CHN CTR",
                          "WOODINVILLE TREATMEN",
                          "WOODLAND AREA",
                          "WOODLAND HALL",
                          "WOODLAND UNKNOWN",
                          "WORLDKIDS SCHOOL",
                          "WRESTLING COACH",
                          "WSMC I",
                          "YACOLT UNKNOWN",
                          "YAKIMA MEMORIAL HOSP",
                          "YES HOUSE",
                          "YES RAINIER HOUSE",
                          "YMCA-JACKSON ELEM",
                          "YMCA AT CHLOE CLARK",
                          "YMCA BAILEY GAZERT",
                          "YMCA BARKLEY",
                          "YMCA BELLEVUE FAMILY",
                          "YMCA CENTRAL CAMP",
                          "YMCA CHILDCARE",
                          "YMCA CHILDRENS CTR",
                          "YMCA DAYCARE",
                          "YMCA EVERGREEN SCH",
                          "YMCA FAMILY SVCS",
                          "YMCA INFANT CENTER",
                          "YMCA LAKE HEIGHTS",
                          "YMCA LINCOLN ELEM",
                          "YMCA NORTHSHORE",
                          "YMCA SCHOOL CARE",
                          "YMCA SCHOOLAGE",
                          "YMCA SKAGIT VALLEY",
                          "YMCA SUMMER DAY",
                          "YMCA SUMMER DAY CAMP",
                          "YMCA THURGOOD MARSHA",
                          "YOUNG CHILD ACADEMY",
                          "YOUNG MINDS",
                          "YOUTH EDUCATION",
                          "YOUTH EDUCATION LL",
                          "YOUTH EDUCATIONAL SE",
                          "YOUTH HAVEN BELLEVUE",
                          "YOUTH SERVICES",
                          "YOUTHCARE SHELTER",
                          "YWCA FAMILY VILLAGE",
                          "YWCA MY FRIENDS")

# Identifiers in this table are from ID_PRSN.
ca_ods_alleg_removal <- read_csv("./raw_data/famlink/ca_ods_allegation_removal.csv",
                                 na = "NULL")

# All persons involved in allegations or removals
ca_ods_id_prsn <- ca_ods_alleg_removal %>% 
  select(child_id) %>% 
  rename(ID_PRSN = child_id) %>% 
  bind_rows(ca_ods_alleg_removal %>% select(parent_id) %>% rename(ID_PRSN = parent_id)) %>% 
  group_by(ID_PRSN) %>% 
  count() %>% 
  ungroup()

# Limit to people involved in allegations or removals.
# Fill in middle name with middle initial if blank.
# Fill in gender if blank and a gendered prefix is specified.
# 12/24/2021 exclude over 2000 records for unborn child and ~ 275 "UNKNOWN CHILD"
famlink_people <- famlink %>% 
  filter(ID_PRSN %in% ca_ods_id_prsn$ID_PRSN & !toupper(NM_LAST) %in% famlink_invalid_last &
           toupper(substr(NM_FIRST,1,6)) != "UNBORN" &
           (paste0(toupper(trimws(NM_FIRST, "both")),toupper(trimws(NM_LAST, "both"))) != "UNKNOWNCHILD")) %>% 
  select(ID_PEOPLE_DIM, ID_PRSN, NM_LAST, NM_FIRST, NM_MIDDLE, NM_MIDDLE_INTL, NM_SFX,
         DT_BIRTH, DT_DEATH, CD_GNDR, NM_PRFX, ID_PEOPLE_DIM_MOM, ID_PRSN_MOM, 
         ID_PEOPLE_DIM_DAD, ID_PRSN_DAD) %>% 
  mutate(id_conglomerate = paste0(ID_PEOPLE_DIM,"famlink"),
         id_source_record = as.character(ID_PEOPLE_DIM),
         source_data = "CW Involvement and Risk for Injury Study.rpt_edited.txt",
         tx_record_relation = "famlink",
         tx_last_name = toupper(NM_LAST),
         tx_first_name = str_replace(toupper(NM_FIRST),
                                     "AUNT[:space:]|UNCLE[:space:]",
                                     ""),
         tx_middle_name = ifelse(!is.na(NM_MIDDLE) & NM_MIDDLE != "NULL",
                                 toupper(NM_MIDDLE),
                                 ifelse(!is.na(NM_MIDDLE_INTL) & NM_MIDDLE_INTL != "NULL",
                                        toupper(NM_MIDDLE_INTL),
                                        NA)),
         tx_suffix_name = toupper(ifelse(NM_SFX == "NULL",
                                         NA,
                                         NM_SFX)),
         dt_birth = ifelse(DT_BIRTH == "NULL",
                           NA,
                           DT_BIRTH),
         dt_death = ifelse(DT_DEATH == "NULL",
                           NA,
                           DT_DEATH),
         dt_birth = as.character(format(date(dt_birth),"%Y%m%d")),
         dt_death = as.character(format(date(dt_death),"%Y%m%d")),
         tx_reported_sex_or_gender = ifelse(CD_GNDR %in% c("F","M"),
                                            CD_GNDR,
                                            case_when(NM_PRFX %in% c("Miss","Mrs.","Ms.") ~ "F",
                                                      NM_PRFX == "Mr." ~ "M")),
         ID_PEOPLE_DIM = as.character(ID_PEOPLE_DIM),
         ID_PRSN = as.character(ID_PRSN))
# For some reason there are people in the allegation/removal table who
# aren't in the FAMLINK list of all parents and children in WA.
famlink_missing <- ca_ods_id_prsn %>% 
  left_join(famlink, by = "ID_PRSN") %>% 
  filter(is.na(ID_PEOPLE_DIM)) %>% 
  arrange(ID_PRSN)
# ID_PRSN 100258287 - 103598162. Allegations/removals are probably more up to date
# than person dump from whenever that was.

# Match child record to mom record by ID_PRSN
famlink_matchmom <- famlink_people %>% 
  select(ID_PEOPLE_DIM, ID_PRSN, ID_PRSN_MOM) %>% 
  filter(ID_PRSN_MOM != "NULL") %>%
  rename(ID_PEOPLE_DIM_CHILD = ID_PEOPLE_DIM,
         ID_PRSN_CHILD = ID_PRSN,
         ID_PRSN = ID_PRSN_MOM) %>% 
  inner_join(famlink_people, by = "ID_PRSN") %>% 
  select(-ID_PEOPLE_DIM_MOM,-ID_PRSN_MOM,-ID_PRSN_DAD) %>% 
  rename(tx_mom_last_name = tx_last_name,
         tx_mom_first_name = tx_first_name,
         tx_mom_middle_name = tx_middle_name,
         dt_mom_dob = dt_birth,
         ID_PEOPLE_DIM_MOM = ID_PEOPLE_DIM,
         ID_PEOPLE_DIM = ID_PEOPLE_DIM_CHILD,
         ID_PRSN_MOM = ID_PRSN,
         ID_PRSN = ID_PRSN_CHILD) %>% 
  select(ID_PEOPLE_DIM,
         tx_mom_last_name,
         tx_mom_first_name,
         tx_mom_middle_name,
         dt_mom_dob)

# Match child record to dad record by ID_PRSN
famlink_matchdad <- famlink_people %>% 
  select(ID_PEOPLE_DIM, ID_PRSN, ID_PRSN_DAD) %>% 
  filter(ID_PRSN_DAD != "NULL") %>%
  rename(ID_PEOPLE_DIM_CHILD = ID_PEOPLE_DIM,
         ID_PRSN_CHILD = ID_PRSN,
         ID_PRSN = ID_PRSN_DAD) %>% 
  inner_join(famlink_people, by = "ID_PRSN") %>% 
  select(-ID_PEOPLE_DIM_DAD,-ID_PRSN_MOM,-ID_PRSN_DAD) %>% 
  rename(tx_dad_last_name = tx_last_name,
         tx_dad_first_name = tx_first_name,
         tx_dad_middle_name = tx_middle_name,
         tx_dad_suffix_name = tx_suffix_name,
         dt_dad_dob = dt_birth,
         ID_PEOPLE_DIM_DAD = ID_PEOPLE_DIM,
         ID_PEOPLE_DIM = ID_PEOPLE_DIM_CHILD,
         ID_PRSN_DAD = ID_PRSN,
         ID_PRSN = ID_PRSN_CHILD) %>% 
  select(ID_PEOPLE_DIM,
         tx_dad_last_name,
         tx_dad_first_name,
         tx_dad_middle_name,
         tx_dad_suffix_name,
         dt_dad_dob)

# Merge parents to child, select fields for linking model
famlink_for_glue <- famlink_people %>% 
  left_join(famlink_matchmom,
            by = "ID_PEOPLE_DIM") %>% 
  left_join(famlink_matchdad,
            by = "ID_PEOPLE_DIM") %>% 
  select(
    id_conglomerate,
    id_source_record,
    source_data,
    tx_record_relation,
    tx_last_name,
    tx_first_name,
    tx_middle_name,
    tx_suffix_name,
    dt_birth,
    dt_death,
    tx_reported_sex_or_gender,
    tx_dad_last_name,
    tx_dad_first_name,
    tx_dad_middle_name,
    tx_dad_suffix_name,
    tx_mom_last_name,
    tx_mom_first_name,
    tx_mom_middle_name
  )
save(famlink_for_glue,file="famlink_for_glue.Rdata")

#load("famlink_for_glue.Rdata")

# 4/29/2021 process death records.
# There are 9 DOBs that fail to parse. They are all from 2016-2017 and have 99 entered as month or day,
# or 99/99/9999 for the whole date. Date parts are available in other fields, so it is not necessary
# to salvage anything from DOB.
death <- read_linkage_data(pii_type = "death_name")
save(death,file="death.Rdata")

#load("death.Rdata")
# 12/9/2021: Fix accidental NA: Date formats changed in 2010 from mm/dd/yyyy to yyyymmdd.
death_tolink <- death %>% 
  mutate(    
    year = as.numeric(str_extract(source_data,"(?<=NamesF)[[:digit:]]{4}")),
    id_conglomerate = paste0(CERT_NUM,"death"),
             id_source_record = CERT_NUM,
             tx_record_relation = "death",
             id_death_certificate = CERT_NUM,
             tx_last_name = LAST_NAME,
             tx_maiden_name = NA,
             tx_first_name = FIRST_NAME,
             tx_middle_name = MIDDLE_NAME,
             tx_suffix_name = SUFFIX,
             dt_birth = ifelse(year < 2010,
                               as.character(format(as.Date(DOB,format = "%d%b%Y"), "%Y%m%d")),
                               DOB),
    dt_birth_yr = substr(dt_birth,1,4),
    dt_birth_mo = substr(dt_birth,5,6),
    dt_birth_da = substr(dt_birth,7,8),
             dt_death = ifelse(year < 2010,
                               as.character(format(as.Date(DATE_OF_DEATH,format = "%d%b%Y"), "%Y%m%d")),
                               DATE_OF_DEATH),
             tx_zip_code = RES_ZIP,
             tx_reported_sex_or_gender = SEX
  )  %>%
  select(
    year,
    id_conglomerate,
    id_source_record,
    source_data,
    tx_record_relation,
    id_death_certificate,
    tx_last_name,
    tx_maiden_name,
    tx_first_name,
    tx_middle_name,
    tx_suffix_name,
    dt_birth,
    dt_birth_yr,
    dt_birth_mo,
    dt_birth_da,
    dt_death,
    tx_zip_code,
    tx_reported_sex_or_gender
  )


# 3/9/2021 splitting the birth data up so different schema can be applied to 2017
# (and beyond, someday)
birth <- read_linkage_data(pii_type = "birth")
save(birth,file="birth.Rdata")

#load("birth.Rdata")
# Data dictionary does not contain documentation on some variables, like
# Child_Calculated_Ethnicity (codes look like Mother_Hispanic) and 
# Child_Calculated_Race (codes look like Mother_Race_Calculation).
# Technical documentation says 2017 was last year that calculated child
# race/ethnicity were included. Probably correspond to raceccal and hispccal
# from prior years.
child2017 <- birth %>% 
  filter(as.numeric(str_extract(source_data,"(?<=bir)[[:digit:]]{4}")) > 2016) %>% 
  mutate(
    year = as.numeric(str_extract(source_data,"(?<=bir)[[:digit:]]{4}")),
    id_source_record = State_File_Number,
    tx_record_relation = "child",
    id_death_certificate = NA,
    dt_cdob = as.character(format(Date_of_Birth, "%Y%m%d")),
    dt_cdob_yr = as.character(Date_of_Birth_Year),
    dt_cdob_mo = as.character(Date_of_Birth_Month),
    dt_cdob_da = as.character(Date_of_Birth_Day),
    tx_last_name = Child_Last_Name,
    tx_maiden_name = NA,
    tx_first_name = Child_First_Name,
    tx_middle_name = Child_Middle_Name,
    tx_suffix_name = Child_Suffix,
    dt_birth = as.character(format(Date_of_Birth, "%Y%m%d")),
    dt_birth_yr = as.character(Date_of_Birth_Year),
    dt_birth_mo = as.character(Date_of_Birth_Month),
    dt_birth_da = as.character(Date_of_Birth_Day),
    dt_death = as.character(format(Date_of_Death, "%Y%m%d")),
    tx_zip_code = Mother_Residence_Zip,
    tx_reported_sex_or_gender = Sex,
    fl_any_hispanic = ifelse(Child_Calculated_Ethnicity %in% c("1","2","3","4","5") |
                               Child_Calculated_Race %in% c("C") |
                               Mother_Hispanic_Mexican == "H" |
                               Mother_Hispanic_Puerto_Rican == "H" |
                               Mother_Hispanic_Cuban == "H" |
                               Mother_Hispanic_Other == "H" |
                               Mother_Hispanic %in% c("1","2","3","4","5") |
                               Mother_Race_Calculation == "C" |
                               Father_Hispanic_Mexican == "H" |
                               Father_Hispanic_Puerto_Rican == "H" |
                               Father_Hispanic_Cuban == "H" |
                               Father_Hispanic_Other == "H" |
                               Father_Hispanic %in% c("1","2","3","4","5") |
                               Father_Race_Calculation == "C", 1, 0),
    fl_any_african_american = ifelse(Child_Calculated_Race == "2" | 
                                       Mother_Race_Black == "Y" | Mother_Race_Calculation == "2" |
                                       Father_Race_Black == "Y" | Father_Race_Calculation == "2", 1, 0),
    fl_any_american_indian = ifelse(Child_Calculated_Race == "3" | 
                                    Mother_Race_Amer_Indian_Alaskan == "Y" |
                                    Mother_Race_Calculation == "3" |
                                    Father_Race_Amer_Indian_Alaskan == "Y" |
                                    Father_Race_Calculation == "3", 1, 0),
    fl_any_asian = ifelse(Child_Calculated_Race %in% c("4","5", "D", "E", "G") |
                          Mother_Race_Asian_Indian == "Y" |
                          Mother_Race_Chinese == "Y" |
                          Mother_Race_Japanese == "Y" |
                          Mother_Race_Korean == "Y" |
                          Mother_Race_Vietnamese == "Y" |
                          Mother_Race_Other_Asian == "Y" |
                          Mother_Race_Calculation %in% c("4","5", "D", "E", "G") |
                          Father_Race_Asian_Indian == "Y" |
                          Father_Race_Chinese == "Y" |
                          Father_Race_Japanese == "Y" |
                          Father_Race_Korean == "Y" |
                          Father_Race_Vietnamese == "Y" |
                          Father_Race_Other_Asian == "Y" |
                          Father_Race_Calculation %in% c("4","5", "D", "E", "G"), 1, 0),
    fl_any_pac_island = ifelse(Child_Calculated_Race %in% c("A", "B", "F", "H", "7") |
                               Mother_Race_Filipino == "Y" |
                               Mother_Race_Hawaiian == "Y" |
                               Mother_Race_Guam_or_Chamorro == "Y" |
                               Mother_Race_Samoan == "Y" |
                               Mother_Race_Other_PI == "Y" |
                               Mother_Race_Calculation %in% c("A", "B", "F", "H", "7") |
                               Father_Race_Filipino == "Y" |
                               Father_Race_Hawaiian == "Y" |
                               Father_Race_Guam_or_Chamorro == "Y" |
                               Father_Race_Samoan == "Y" |
                               Father_Race_Other_PI == "Y" |
                               Father_Race_Calculation %in% c("A", "B", "F", "H", "7"), 1, 0),
    fl_any_white = ifelse(Child_Calculated_Race == "1" | Mother_Race_Calculation == "1" |
                          Father_Race_Calculation == "1", 1, 0),
    tx_dad_last_name = Father_Last_Name,
    tx_dad_first_name = Father_First_Name,
    tx_dad_middle_name = Father_Middle_Name,
    tx_dad_suffix_name = NA,
    dt_dad_dob = as.character(format(Father_Date_of_Birth, "%Y%m%d")),
    dt_dad_dob_yr = as.character(Father_Date_of_Birth_Year),
    dt_dad_dob_mo = as.character(Father_Date_of_Birth_Month),
    dt_dad_dob_da = as.character(Father_Date_of_Birth_Day),
    fl_any_hispanic_dad = ifelse(Father_Hispanic %in% c("1","2","3","4","5") | 
                                 Father_Hispanic_Mexican == "H" |
                                 Father_Hispanic_Puerto_Rican == "H" |
                                 Father_Hispanic_Cuban == "H" |
                                 Father_Hispanic_Other == "H" |
                                 Father_Race_Calculation %in% c("C"), 1, 0),
    fl_any_african_american_dad = ifelse(Father_Race_Black == "Y" |
                                           Father_Race_Calculation %in% c("2"), 1, 0),
    fl_any_american_indian_dad = ifelse(Father_Race_Amer_Indian_Alaskan == "Y" |
                                          Father_Race_Calculation == "3", 1, 0),
    fl_any_asian_dad = ifelse(Father_Race_Asian_Indian == "Y" |
                              Father_Race_Chinese == "Y" |
                              Father_Race_Japanese == "Y" |
                              Father_Race_Korean == "Y" |
                              Father_Race_Vietnamese == "Y" |
                              Father_Race_Other_Asian == "Y" |
                              Father_Race_Calculation %in% c("4","5", "D", "E", "G"), 1, 0),
    fl_any_pac_island_dad = ifelse(Father_Race_Filipino == "Y" |
                                   Father_Race_Hawaiian == "Y" |
                                   Father_Race_Guam_or_Chamorro == "Y" |
                                   Father_Race_Samoan == "Y" |
                                   Father_Race_Other_PI == "Y" |
                                   Father_Race_Calculation %in% c("A", "B", "F", "H", "7"), 1, 0),
    fl_any_white_dad = ifelse(Father_Race_Calculation == "1", 1, 0),
    tx_mom_last_name = ifelse(is.na(Mother_Legal_Last_Name) | Mother_Legal_Last_Name == "",
                              Mother_Maiden_Name,
                              Mother_Legal_Last_Name),
    tx_mom_maiden_name = Mother_Maiden_Name,
    tx_mom_first_name = Mother_First_Name,
    tx_mom_middle_name = Mother_Middle_Name,
    dt_mom_dob = as.character(format(Mother_Date_of_Birth, "%Y%m%d")),
    dt_mom_dob_yr = as.character(Mother_Date_of_Birth_Year),
    dt_mom_dob_mo = as.character(Mother_Date_of_Birth_Month),
    dt_mom_dob_da = as.character(Mother_Date_of_Birth_Day),
    fl_any_hispanic_mom = ifelse(Mother_Hispanic_Mexican == "H" |
                                 Mother_Hispanic_Puerto_Rican == "H" |
                                 Mother_Hispanic_Cuban == "H" |
                                 Mother_Hispanic_Other == "H" |
                                 Mother_Hispanic %in% c("1","2","3","4","5") | 
                                 Mother_Race_Calculation == "C", 1, 0),
    fl_any_african_american_mom = ifelse(Mother_Race_Black == "Y" | 
                                         Mother_Race_Calculation == "2", 1, 0),
    fl_any_american_indian_mom = ifelse(Mother_Race_Amer_Indian_Alaskan == "Y" |
                                        Mother_Race_Calculation == "3", 1, 0),
    fl_any_asian_mom = ifelse(Mother_Race_Asian_Indian == "Y" |
                              Mother_Race_Chinese == "Y" |
                              Mother_Race_Japanese == "Y" |
                              Mother_Race_Korean == "Y" |
                              Mother_Race_Vietnamese == "Y" |
                              Mother_Race_Other_Asian == "Y" |
                              Mother_Race_Calculation %in% c("4","5", "D", "E", "G"), 1, 0),
    fl_any_pac_island_mom = ifelse(Mother_Race_Filipino == "Y" |
                                   Mother_Race_Hawaiian == "Y" |
                                   Mother_Race_Guam_or_Chamorro == "Y" |
                                   Mother_Race_Samoan == "Y" |
                                   Mother_Race_Other_PI == "Y" |
                                   Mother_Race_Calculation %in% c("A", "B", "F", "H", "7"), 1, 0),
    fl_any_white_mom = ifelse(Mother_Race_Calculation == "1", 1, 0),  
    fl_child_death_cert_oos = NA,
    dt_youngest_maternal_sibling_birth = ifelse(is.na(Last_Live_Birth_Year),NA,
                                                paste0(Last_Live_Birth_Year,
                                                       str_pad(Last_Live_Birth_Month,2,"left","0"))),
    fl_child_death_in_hospital = ifelse(Child_Alive == "N", 1, 0)  ) %>%
  select(
    year,
    id_source_record,
    source_data,
    tx_record_relation,
    id_death_certificate,
    dt_cdob,
    dt_cdob_yr,
    dt_cdob_mo,
    dt_cdob_da,
    tx_last_name,
    tx_maiden_name,
    tx_first_name,
    tx_middle_name,
    tx_suffix_name,
    fl_any_hispanic,
    fl_any_african_american,
    fl_any_american_indian,
    fl_any_asian,
    fl_any_pac_island,
    fl_any_white,   
    dt_birth,
    dt_birth_yr,
    dt_birth_mo,
    dt_birth_da,
    dt_death,
    tx_zip_code,
    tx_reported_sex_or_gender,
    tx_dad_last_name,
    tx_dad_first_name,
    tx_dad_middle_name,
    tx_dad_suffix_name,
    fl_any_hispanic_dad,
    fl_any_african_american_dad,
    fl_any_american_indian_dad,
    fl_any_asian_dad,
    fl_any_pac_island_dad,
    fl_any_white_dad,       
    dt_dad_dob,
    dt_dad_dob_yr,
    dt_dad_dob_mo,
    dt_dad_dob_da,
    tx_mom_last_name,
    tx_mom_maiden_name,
    tx_mom_first_name,
    tx_mom_middle_name, 
    fl_any_hispanic_mom,
    fl_any_african_american_mom,
    fl_any_american_indian_mom,
    fl_any_asian_mom,
    fl_any_pac_island_mom,
    fl_any_white_mom,      
    dt_mom_dob,
    dt_mom_dob_yr,
    dt_mom_dob_mo,
    dt_mom_dob_da,
    fl_child_death_cert_oos,
    dt_youngest_maternal_sibling_birth,
    fl_child_death_in_hospital
  )


children <- birth %>%
  filter(as.numeric(str_extract(source_data,"(?<=bir)[[:digit:]]{4}")) < 2017) %>% 
  mutate(
    year = as.numeric(str_extract(source_data,"(?<=bir)[[:digit:]]{4}")),
    id_source_record = CERT_NUM,
    tx_record_relation = "child",
    id_death_certificate = ifelse(DEATH_CERT_NUM_OOS != "000000", DEATH_CERT_NUM_OOS, 
                                  ifelse(DEATH_CERT_NUM != "0000000000", DEATH_CERT_NUM, NA
                                  )),
    dt_cdob = PERSON_DOB,
    dt_cdob_yr = substr(PERSON_DOB,1,4),
    dt_cdob_mo = substr(PERSON_DOB,5,6),
    dt_cdob_da = substr(PERSON_DOB,7,8),
    dt_birth_yr = dt_cdob_yr,
    dt_birth_mo = dt_cdob_mo,
    dt_birth_da = dt_cdob_da,
    tx_last_name = PERSON_LAST_NAME,
    tx_maiden_name = NA,
    tx_first_name = PERSON_FIRST_NAME,
    tx_middle_name = PERSON_MIDDLE_NAME,
    tx_suffix_name = PERSON_SUFFIX,
    dt_birth = PERSON_DOB,
    dt_death = DATE_OF_DEATH,
    tx_zip_code = RES_ZIP_CODE,
    tx_reported_sex_or_gender = SEX,
    fl_any_hispanic = ifelse(PERSON_HISP_CALC %in% c("1","2","3","4","5") | 
                               PERSON_RACE_CALC %in% c("C"), 1, 0),
    fl_any_african_american = ifelse(PERSON_RACE_CALC %in% c("2"), 1, 0),
    fl_any_american_indian = ifelse(PERSON_RACE_CALC %in% c("3"), 1, 0),
    fl_any_asian = ifelse(PERSON_RACE_CALC %in% c("4","5", "D", "E", "G"), 1, 0),
    fl_any_pac_island = ifelse(PERSON_RACE_CALC %in% c("A", "B", "F", "H", "7"), 1, 0),
    fl_any_white = ifelse(PERSON_RACE_CALC %in% c("1"), 1, 0),
    tx_dad_last_name = FA_LAST_NAME,
    tx_dad_first_name = FA_FIRST_NAME,
    tx_dad_middle_name = FA_MIDDLE_NAME,
    tx_dad_suffix_name = FA_SUFFIX,
    dt_dad_dob = FA_BIOLOGICAL_DOB,
    fl_any_hispanic_dad = ifelse(FA_HISPANIC %in% c("1","2","3","4","5") | 
                                   FA_RACE %in% c("C"), 1, 0),
    fl_any_african_american_dad = ifelse(FA_RACE %in% c("2"), 1, 0),
    fl_any_american_indian_dad = ifelse(FA_RACE %in% c("3"), 1, 0),
    fl_any_asian_dad = ifelse(FA_RACE %in% c("4","5", "D", "E", "G"), 1, 0),
    fl_any_pac_island_dad = ifelse(FA_RACE %in% c("A", "B", "F", "H", "7"), 1, 0),
    fl_any_white_dad = ifelse(FA_RACE %in% c("1"), 1, 0),
    tx_mom_last_name = ifelse(is.na(MO_LEGAL_NAME) | MO_LEGAL_NAME == "",
                              MO_MAIDEN_NAME,
                              MO_LEGAL_NAME),
    tx_mom_maiden_name = MO_MAIDEN_NAME,
    tx_mom_first_name = MO_FIRST_NAME,
    tx_mom_middle_name = MO_MIDDLE_NAME,
    dt_mom_dob = MO_BIOLOGICAL_DOB,
    fl_any_hispanic_mom = ifelse(MO_HISPANIC %in% c("1","2","3","4","5") | 
                                   MO_RACE %in% c("C"), 1, 0),
    fl_any_african_american_mom = ifelse(MO_RACE %in% c("2"), 1, 0),
    fl_any_american_indian_mom = ifelse(MO_RACE %in% c("3"), 1, 0),
    fl_any_asian_mom = ifelse(MO_RACE %in% c("4","5", "D", "E", "G"), 1, 0),
    fl_any_pac_island_mom = ifelse(MO_RACE %in% c("A", "B", "F", "H", "7"), 1, 0),
    fl_any_white_mom = ifelse(MO_RACE %in% c("1"), 1, 0),  
    fl_child_death_cert_oos = ifelse(DEATH_CERT_NUM_OOS != "000000", 1, 0),
    dt_youngest_maternal_sibling_birth = DATE_LAST_BIRTH,
    fl_child_death_in_hospital = ifelse(PERSON_ALIVE_AT_DISCHARGE == "N", 1, 0)
  ) %>%
  select(
    year,
    id_source_record,
    source_data,
    tx_record_relation,
    id_death_certificate,
    dt_cdob,
    dt_cdob_yr,
    dt_cdob_mo,
    dt_cdob_da,
    dt_birth_yr,
    dt_birth_mo,
    dt_birth_da,
    tx_last_name,
    tx_maiden_name,
    tx_first_name,
    tx_middle_name,
    tx_suffix_name,
    fl_any_hispanic,
    fl_any_african_american,
    fl_any_american_indian,
    fl_any_asian,
    fl_any_pac_island,
    fl_any_white,   
    dt_birth,
    dt_death,
    tx_zip_code,
    tx_reported_sex_or_gender,
    tx_dad_last_name,
    tx_dad_first_name,
    tx_dad_middle_name,
    tx_dad_suffix_name,
    fl_any_hispanic_dad,
    fl_any_african_american_dad,
    fl_any_american_indian_dad,
    fl_any_asian_dad,
    fl_any_pac_island_dad,
    fl_any_white_dad,       
    dt_dad_dob,
    tx_mom_last_name,
    tx_mom_maiden_name,
    tx_mom_first_name,
    tx_mom_middle_name, 
    fl_any_hispanic_mom,
    fl_any_african_american_mom,
    fl_any_american_indian_mom,
    fl_any_asian_mom,
    fl_any_pac_island_mom,
    fl_any_white_mom,      
    dt_mom_dob,
    fl_child_death_cert_oos,
    dt_youngest_maternal_sibling_birth,
    fl_child_death_in_hospital
  ) %>% 
  bind_rows(child2017) %>% 
  mutate(id_conglomerate = paste0(id_source_record, tx_record_relation))


mothers <- children %>%
  mutate(
    tx_record_relation = "mother",
    id_conglomerate = paste0(id_source_record, tx_record_relation),
    id_death_certificate = NA,
    tx_last_name = tx_mom_last_name,
    tx_maiden_name = tx_mom_maiden_name,
    tx_first_name = tx_mom_first_name,
    tx_middle_name = tx_mom_middle_name,
    tx_suffix_name = NA,
    dt_birth = dt_mom_dob,
    dt_birth_yr = dt_mom_dob_yr,
    dt_birth_mo = dt_mom_dob_mo,
    dt_birth_da = dt_mom_dob_da,
    dt_death = NA,
    tx_reported_sex_or_gender = "F",
    fl_any_hispanic = fl_any_hispanic_mom,
    fl_any_african_american = fl_any_african_american_mom,
    fl_any_american_indian = fl_any_american_indian_mom,
    fl_any_asian = fl_any_asian_mom,
    fl_any_pac_island = fl_any_pac_island_mom,
    fl_any_white = fl_any_white_mom,
    tx_dad_last_name = tx_dad_last_name,
    tx_dad_first_name = tx_dad_first_name,
    tx_dad_middle_name = tx_dad_middle_name,
    tx_dad_suffix_name = tx_dad_suffix_name,
    dt_dad_dob = dt_dad_dob,
    dt_dad_dob_yr = dt_dad_dob_yr,
    dt_dad_dob_mo = dt_dad_dob_mo,
    dt_dad_dob_da = dt_dad_dob_da,
    fl_any_hispanic_dad = NA,
    fl_any_african_american_dad = NA,
    fl_any_american_indian_dad = NA,
    fl_any_asian_dad = NA,
    fl_any_pac_island_dad = NA,
    fl_any_white_dad = NA,
    tx_mom_last_name = NA,
    tx_mom_maiden_name = NA,
    tx_mom_first_name = NA,
    tx_mom_middle_name = NA,
    dt_mom_dob = NA,
    dt_mom_dob_yr = NA,
    dt_mom_dob_mo = NA,
    dt_mom_dob_da = NA,
    fl_any_hispanic_mom = NA,
    fl_any_african_american_mom = NA,
    fl_any_american_indian_mom = NA,
    fl_any_asian_mom = NA,
    fl_any_pac_island_mom = NA,
    fl_any_white_mom = NA,
    fl_child_death_cert_oos = NA,
    dt_youngest_maternal_sibling_birth = NA,
    fl_child_death_in_hospital = NA
  ) 

fathers <- children %>%
  mutate(
    tx_record_relation = "father",
    id_conglomerate = paste0(id_source_record, tx_record_relation),
    id_death_certificate = NA,
    dt_cdob = dt_birth,
    tx_last_name = tx_dad_last_name,
    tx_maiden_name = NA,
    tx_first_name = tx_dad_first_name,
    tx_middle_name = tx_dad_middle_name,
    tx_suffix_name = tx_dad_suffix_name,
    dt_birth = dt_dad_dob,
    dt_birth_yr = dt_dad_dob_yr,
    dt_birth_mo = dt_dad_dob_mo,
    dt_birth_da = dt_dad_dob_da,
    dt_death = NA,
    tx_reported_sex_or_gender = "M",
    fl_any_hispanic = fl_any_hispanic_dad,
    fl_any_african_american = fl_any_african_american_dad,
    fl_any_american_indian = fl_any_american_indian_dad,
    fl_any_asian = fl_any_asian_dad,
    fl_any_pac_island = fl_any_pac_island_dad,
    fl_any_white = fl_any_white_dad,
    tx_dad_last_name = NA,
    tx_dad_first_name = NA,
    tx_dad_middle_name = NA,
    tx_dad_suffix_name = NA,
    dt_dad_dob = NA,
    dt_dad_dob_yr = NA,
    dt_dad_dob_mo = NA,
    dt_dad_dob_da = NA,
    fl_any_hispanic_dad = NA,
    fl_any_african_american_dad = NA,
    fl_any_american_indian_dad = NA,
    fl_any_asian_dad = NA,
    fl_any_pac_island_dad = NA,
    fl_any_white_dad = NA,
    tx_mom_last_name = tx_mom_last_name,
    tx_mom_maiden_name = tx_mom_maiden_name,
    tx_mom_first_name = tx_mom_first_name,
    tx_mom_middle_name = tx_mom_middle_name,
    dt_mom_dob = dt_mom_dob,
    dt_mom_dob_yr = dt_mom_dob_yr,
    dt_mom_dob_mo = dt_mom_dob_mo,
    dt_mom_dob_da = dt_mom_dob_da,
    fl_any_hispanic_mom = NA,
    fl_any_african_american_mom = NA,
    fl_any_american_indian_mom = NA,
    fl_any_asian_mom = NA,
    fl_any_pac_island_mom = NA,
    fl_any_white_mom = NA,
    fl_child_death_cert_oos = NA,
    dt_youngest_maternal_sibling_birth = NA,
    fl_child_death_in_hospital = NA
  ) 

# The raw files take a long time to read. Use the saved multi-year data set once
# it exists.
patients <- read_linkage_data(pii_type = "chars") %>%
  mutate(
    year = as.numeric(str_extract(source_data,"[[:digit:]]{4}(?=\\.sas)")),
    id_source_record = SEQ_NO_ENC,
    tx_record_relation = "patient",
    id_conglomerate = paste0(id_source_record, tx_record_relation),
    id_death_certificate = NA,
    dt_cdob = ifelse(ADM_TYPE == 4 | (ADM_DATE <= DOB & DOB <= DIS_DATE),
                     as.character(format(DOB, "%Y%m%d")),
                     NA),
    tx_last_name = LASTNAME,
    tx_maiden_name = NA,
    tx_first_name = FIRSTNAME,
    tx_middle_name = MINAME,
    tx_suffix_name = NA,
    dt_birth = as.character(format(DOB, "%Y%m%d")),
    dt_death = NA,
    tx_zip_code = ZIPCODE,
    tx_reported_sex_or_gender = SEX,
    fl_any_hispanic = ifelse(HISPANIC %in% c("Y"), 1, 0),
    fl_any_african_american = ifelse(RACE_BLK %in% c("Y"), 1, 0),
    fl_any_american_indian = ifelse(RACE_AMI %in% c("Y"), 1, 0),
    fl_any_asian = ifelse(RACE_ASI %in% c("Y"), 1, 0),
    fl_any_pac_island = ifelse(RACE_HAW %in% c("Y"), 1, 0),
    fl_any_white = ifelse(RACE_WHT %in% c("Y"), 1, 0),
    tx_dad_last_name = NA,
    tx_dad_first_name = NA,
    tx_dad_middle_name = NA,
    tx_dad_suffix_name = NA,
    dt_dad_dob = NA,
    fl_any_hispanic_dad = NA,
    fl_any_african_american_dad = NA,
    fl_any_american_indian_dad = NA,
    fl_any_asian_dad = NA,
    fl_any_pac_island_dad = NA,
    fl_any_white_dad = NA,
    tx_mom_last_name = NA,
    tx_mom_maiden_name = NA,
    tx_mom_first_name = NA,
    tx_mom_middle_name = NA,
    dt_mom_dob = NA,
    fl_any_hispanic_mom = NA,
    fl_any_african_american_mom = NA,
    fl_any_american_indian_mom = NA,
    fl_any_asian_mom = NA,
    fl_any_pac_island_mom = NA,
    fl_any_white_mom = NA,
    fl_child_death_cert_oos = NA,
    dt_youngest_maternal_sibling_birth = NA,
    fl_child_death_in_hospital = NA
  )  %>%
  select(
    year,
    id_source_record,
    source_data,
    id_conglomerate,
    tx_record_relation,
    id_death_certificate,
    dt_cdob,
    tx_last_name,
    tx_maiden_name,
    tx_first_name,
    tx_middle_name,
    tx_suffix_name,
    fl_any_hispanic,
    fl_any_african_american,
    fl_any_american_indian,
    fl_any_asian,
    fl_any_pac_island,
    fl_any_white,
    dt_birth,
    dt_death,
    tx_zip_code,
    tx_reported_sex_or_gender,
    tx_dad_last_name,
    tx_dad_first_name,
    tx_dad_middle_name,
    tx_dad_suffix_name,
    fl_any_hispanic_dad,
    fl_any_african_american_dad,
    fl_any_american_indian_dad,
    fl_any_asian_dad,
    fl_any_pac_island_dad,
    fl_any_white_dad,
    dt_dad_dob,
    tx_mom_last_name,
    tx_mom_maiden_name,
    tx_mom_first_name,
    tx_mom_middle_name,
    fl_any_hispanic_mom,
    fl_any_african_american_mom,
    fl_any_american_indian_mom,
    fl_any_asian_mom,
    fl_any_pac_island_mom,
    fl_any_white_mom,
    dt_mom_dob,
    fl_child_death_cert_oos,
    dt_youngest_maternal_sibling_birth,
    fl_child_death_in_hospital
  )
save(patients,file="patients.Rdata")
#load("patients.Rdata")

# Put everybody together. Remove punctuation and spaces from names. Create 
# truncated name fields.
rodis_people <- bind_rows(
  children,
  mothers,
  fathers,
  patients,
  famlink_for_glue,
  death_tolink) %>% 
  mutate(tx_last_name = gsub("[[:punct:]]|[[:space:]]","",tx_last_name),
         tx_maiden_name = gsub("[[:punct:]]|[[:space:]]","",tx_maiden_name),
         tx_first_name = gsub("[[:punct:]]|[[:space:]]","",tx_first_name),
         tx_middle_name = gsub("[[:punct:]]|[[:space:]]","",tx_middle_name),
         tx_suffix_name = gsub("[[:punct:]]|[[:space:]]","",tx_suffix_name),
         tx_mom_last_name = gsub("[[:punct:]]|[[:space:]]","",tx_mom_last_name),
         tx_mom_maiden_name = gsub("[[:punct:]]|[[:space:]]","",tx_mom_maiden_name),
         tx_mom_first_name = gsub("[[:punct:]]|[[:space:]]","",tx_mom_first_name),
         tx_mom_middle_name = gsub("[[:punct:]]|[[:space:]]","",tx_mom_middle_name),
         tx_dad_last_name = gsub("[[:punct:]]|[[:space:]]","",tx_dad_last_name),
         tx_dad_suffix_name = gsub("[[:punct:]]|[[:space:]]","",tx_dad_suffix_name),
         tx_dad_first_name = gsub("[[:punct:]]|[[:space:]]","",tx_dad_first_name),
         tx_dad_middle_name = gsub("[[:punct:]]|[[:space:]]","",tx_dad_middle_name),
         tx_last_2 = substr(tx_last_name,1,2),
         tx_first_2 = substr(tx_first_name,1,2),
         tx_middle_2 = substr(tx_middle_name,1,2),
         dt_birth_yr = ifelse(dt_birth_yr == "" | is.na(dt_birth_yr),
                              substr(dt_birth,1,4),
                              dt_birth_yr),
         dt_birth_mo = ifelse(dt_birth_mo == "" | is.na(dt_birth_mo),
                              substr(dt_birth,5,6),
                              dt_birth_mo),
         dt_birth_da = ifelse(dt_birth_da == "" | is.na(dt_birth_da),
                              substr(dt_birth,7,8),
                              dt_birth_da),
         dt_cdob_yr = ifelse(dt_cdob_yr == "" | is.na(dt_cdob_yr),
                              substr(dt_cdob,1,4),
                              dt_cdob_yr),
         dt_cdob_mo = ifelse(dt_cdob_mo == "" | is.na(dt_cdob_mo),
                              substr(dt_cdob,5,6),
                              dt_cdob_mo),
         dt_cdob_da = ifelse(dt_cdob_da == "" | is.na(dt_cdob_da),
                              substr(dt_cdob,7,8),
                              dt_cdob_da),
         dt_mom_dob_yr = ifelse(dt_mom_dob_yr == "" | is.na(dt_mom_dob_yr),
                             substr(dt_mom_dob,1,4),
                             dt_mom_dob_yr),
         dt_mom_dob_mo = ifelse(dt_mom_dob_mo == "" | is.na(dt_mom_dob_mo),
                             substr(dt_mom_dob,5,6),
                             dt_mom_dob_mo),
         dt_mom_dob_da = ifelse(dt_mom_dob_da == "" | is.na(dt_mom_dob_da),
                             substr(dt_mom_dob,7,8),
                             dt_mom_dob_da),
         dt_dad_dob_yr = ifelse(dt_dad_dob_yr == "" | is.na(dt_dad_dob_yr),
                                substr(dt_dad_dob,1,4),
                                dt_dad_dob_yr),
         dt_dad_dob_mo = ifelse(dt_dad_dob_mo == "" | is.na(dt_dad_dob_mo),
                                substr(dt_dad_dob,5,6),
                                dt_dad_dob_mo),
         dt_dad_dob_da = ifelse(dt_dad_dob_da == "" | is.na(dt_dad_dob_da),
                                substr(dt_dad_dob,7,8),
                                dt_dad_dob_da))
# Save copy with data types intact so we don't have to read the CHARS data again.
save(rodis_people,file="rodis_people.Rdata")

# Use this code if reading the above file instead of the individual raw files
#load("rodis_people.Rdata")

rodis_people_glue <- rodis_people %>% 
  select(    id_conglomerate,
             id_source_record,
             tx_record_relation,
             tx_last_name,
             tx_maiden_name,
             tx_first_name,
             tx_middle_name,
             tx_suffix_name,
             tx_reported_sex_or_gender,
             tx_mom_last_name,
             tx_mom_maiden_name,
             tx_mom_first_name,
             tx_mom_middle_name,
             dt_mom_dob_yr,
             dt_mom_dob_mo,
             dt_mom_dob_da,
             tx_dad_last_name,
             tx_dad_first_name,
             tx_dad_middle_name,
             tx_dad_suffix_name,
             dt_dad_dob_yr,
             dt_dad_dob_mo,
             dt_dad_dob_da,
             dt_youngest_maternal_sibling_birth,
             tx_last_2,
             tx_first_2,
             tx_middle_2,
             dt_birth_yr,
             dt_birth_mo,
             dt_birth_da,
             dt_cdob_yr,
             dt_cdob_mo,
             dt_cdob_da
           )

# Write data back to Google for linkage work on AWS Glue
write_csv(rodis_people_glue, "rodis_people_glue.csv",na="")
# Save copy with data types intact.
save(rodis_people_glue,file="rodis_people_glue.Rdata")
#load("rodis_people_glue.Rdata")
drive_upload(
  media = "rodis_people_glue.csv",
  name = "rodis_people_glue.csv",
  path = rodis_pii_dribble
)
